import { AppRegistry } from 'react-native';
import Accountant from './Components/Screens/Accountant';
import Header from './Components/Header/Header';
import HeaderManager from './Components/Header/HeaderManager';
import FilterComponent from './Components/Header/FilterComponent';
import HeaderContain from './Components/Header/HeaderContain';
import ManageRequestScreen from './Components/Screens/ManageRequest/ManageRequestScreen';
import CardDetail from './Components/Screens/ManageRequest/CardDetail';
import CardEditHistory from './Components/Screens/ManageRequest/CardEditHistory';
import Filter from './Components/Screens/ManageRequest/Filter';
import Arlam from './Components/Screens/ManageRequest/Arlam';
import Test from './Components/Test';
import DashBoard from './Components/Screens/ManageRequest/DashBoard';
import Login from './Components/Login/Login';
import MakeRequest from './Components/Screens/MakeRequest/MakeRequest';
AppRegistry.registerComponent('VietCom', () => MakeRequest);
